[package]
name = "sleep_spin"
version = "0.1.0"
edition = "2024"
authors = ["Leo Wong <leowong121073@gmail.com>"]
description = "A fast spinlock implementation that yields via nanosleep under high contention."
license = "Apache-2.0"
repository = "https://github.com/leo2006-206/sleep_spin"
readme = "README.md"
keywords = ["spinlock", "mutex", "concurrency", "lock_api", "dclp"]
categories = ["concurrency", "no-std::no-alloc"]

[dependencies]
lock_api = "0.4"

[[bench]]
name = "lock_bench"
harness = false

[dev-dependencies]
parking_lot = "0.12"
spin = "0.9"